image: registry.sindria.org/docker-images/image-builder:latest

stages:
  - build
  - push

before_script:
  - export BLUE='\033[0;34m'
  - export YELLOW='\033[0;33m'
  - export RED='\033[0;31m'
  - export NC='\033[0m' #No Color
  - export NOW=$(date "+%Y-%m-%d_%H-%M-%S")

build_image:
  stage: build
  tags:
    - default
  only:
    - tags
  script:
    - echo -e "${BLUE}Building image...${NC}"
    - chmod +x build.sh
    - ./build.sh 1000 $CI_COMMIT_TAG 7.1
    - ./build.sh 1000 $CI_COMMIT_TAG 7.2
    - ./build.sh 1000 $CI_COMMIT_TAG 7.3
    - ./build.sh 1000 $CI_COMMIT_TAG 7.4
    - cowsay -f tux "Build Success"

push_image:
  stage: push
  tags:
    - default
  only:
    - tags
  script:
    - echo -e "${BLUE}Pushing image into registry...${NC}"
    - docker push registry.sindria.org/docker-images/nginx-php:$CI_COMMIT_TAG-7.1
    - docker push registry.sindria.org/docker-images/nginx-php:$CI_COMMIT_TAG-7.2
    - docker push registry.sindria.org/docker-images/nginx-php:$CI_COMMIT_TAG-7.3
    - docker push registry.sindria.org/docker-images/nginx-php:$CI_COMMIT_TAG-7.4
    - echo #
    - echo -e "${BLUE}Cleaning local registry...${NC}"
    - docker image rm registry.sindria.org/docker-images/nginx-php:$CI_COMMIT_TAG-7.1
    - docker image rm registry.sindria.org/docker-images/nginx-php:$CI_COMMIT_TAG-7.2
    - docker image rm registry.sindria.org/docker-images/nginx-php:$CI_COMMIT_TAG-7.3
    - docker image rm registry.sindria.org/docker-images/nginx-php:$CI_COMMIT_TAG-7.4
    - echo #
    - cowsay -f dragon "Well Done! New docker image is now on your registry."

